In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score
import time

In [2]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=FutureWarning)

In [3]:
fall = pd.read_csv('Dataset/Fall.csv', header = None)
non_fall = pd.read_csv('Dataset/NonFall.csv', header = None)

non_fall[6] = np.zeros(len(non_fall), dtype=int)
fall[6] = np.ones(len(fall), dtype=int)
fall = fall.sample(frac=1).reset_index(drop=True).iloc[:len(non_fall), :]

cmbd_data = pd.concat([fall,non_fall])
cmbd_data = cmbd_data.sample(frac=1).reset_index(drop=True)

data_x = cmbd_data.iloc[:,:6].values
y_inp = cmbd_data.iloc[:,6].values

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_inp = sc.fit_transform(data_x)
print("Mean = {", end="")
for m in sc.mean_:
    print(m, end=",")
print("}")
print("Scale = {", end="")
for s in sc.scale_:
    print(s, end=",")
print("}")

Mean = {-4.00828713357483,-2.2663390575960944,2.869847985595639,-0.3299605730430636,-1.753439539402048,5.006502957021771,}
Scale = {6.163171870275944,5.5564830026680685,5.888023482049667,3.2898309258374496,6.838216404218108,4.574600635818,}


In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_inp,y_inp,random_state = 0)

In [6]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_train)

cm = confusion_matrix(y_train, y_pred)
print("Confusion Matrix (Train Data): \n", cm)
accuracy = accuracy_score(y_train, y_pred)
print("Accuracy (Train Data): {:.2f} %".format(accuracy*100))

startTime = time.time()
y_pred = classifier.predict(x_test)
print("Classification Time per datapoint: ", (time.time() - startTime)/70257)
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix (Test Data): \n", cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy (Test Data): {:.2f} %".format(accuracy*100))

Confusion Matrix (Train Data): 
 [[103016   2295]
 [   937 104521]]
Accuracy (Train Data): 98.47 %
Classification Time per datapoint:  3.105750083176765e-08
Confusion Matrix (Test Data): 
 [[34388   814]
 [  332 34723]]
Accuracy (Test Data): 98.37 %


In [7]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_train)

cm = confusion_matrix(y_train, y_pred)
print("Confusion Matrix (Train Data): \n", cm)
accuracy = accuracy_score(y_train, y_pred)
print("Accuracy (Train Data): {:.2f} %".format(accuracy*100))

startTime = time.time()
y_pred = classifier.predict(x_test)
print("Classification Time per datapoint: ", (time.time() - startTime)/70257)
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix (Test Data): \n", cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy (Test Data): {:.2f} %".format(accuracy*100))

Confusion Matrix (Train Data): 
 [[104967    344]
 [   204 105254]]
Accuracy (Train Data): 99.74 %
Classification Time per datapoint:  8.481433244054703e-05
Confusion Matrix (Test Data): 
 [[35033   169]
 [  111 34944]]
Accuracy (Test Data): 99.60 %


In [8]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state=0) # rbf (Radial Basis function) is same as gaussian kernel 
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_train)

cm = confusion_matrix(y_train, y_pred)
print("Confusion Matrix (Train Data): \n", cm)
accuracy = accuracy_score(y_train, y_pred)
print("Accuracy (Train Data): {:.2f} %".format(accuracy*100))

startTime = time.time()
y_pred = classifier.predict(x_test)
print("Classification Time per datapoint: ", (time.time() - startTime)/70257)
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix (Test Data): \n", cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy (Test Data): {:.2f} %".format(accuracy*100))

Confusion Matrix (Train Data): 
 [[104787    524]
 [   534 104924]]
Accuracy (Train Data): 99.50 %
Classification Time per datapoint:  0.0005572840940660967
Confusion Matrix (Test Data): 
 [[34989   213]
 [  180 34875]]
Accuracy (Test Data): 99.44 %


In [9]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_train)

cm = confusion_matrix(y_train, y_pred)
print("Confusion Matrix (Train Data): \n", cm)
accuracy = accuracy_score(y_train, y_pred)
print("Accuracy (Train Data): {:.2f} %".format(accuracy*100))

startTime = time.time()
y_pred = classifier.predict(x_test)
print("Classification Time per datapoint: ", (time.time() - startTime)/70257)
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix (Test Data): \n", cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy (Test Data): {:.2f} %".format(accuracy*100))

Confusion Matrix (Train Data): 
 [[98137  7174]
 [25696 79762]]
Accuracy (Train Data): 84.40 %
Classification Time per datapoint:  1.8663006072376462e-07
Confusion Matrix (Test Data): 
 [[32804  2398]
 [ 8534 26521]]
Accuracy (Test Data): 84.44 %


In [17]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=3, min_samples_split = 2, min_samples_leaf = 2, criterion='entropy')
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_train)

cm = confusion_matrix(y_train, y_pred)
print("Confusion Matrix (Train Data): \n", cm)
accuracy = accuracy_score(y_train, y_pred)
print("Accuracy (Train Data): {:.2f} %".format(accuracy*100))

startTime = time.time()
y_pred = classifier.predict(x_test)
print("Classification Time per datapoint: ", (time.time() - startTime)/70257)
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix (Test Data): \n", cm)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy (Test Data): {:.2f} %".format(accuracy*100))

Confusion Matrix (Train Data): 
 [[105311      0]
 [     0 105458]]
Accuracy (Train Data): 100.00 %
Classification Time per datapoint:  2.6085314400527927e-07
Confusion Matrix (Test Data): 
 [[35201     1]
 [    0 35055]]
Accuracy (Test Data): 100.00 %


In [18]:
from micromlgen import port

with open("D:\\Documents\\UMass_ECE\\2nd_Sem\\ECE697LP_LowPowerEmbedded\\Project\\ESP32_MPU\\model.h", 'w') as f:
    f.write(port(classifier))

In [ ]:
bandPort.close()

In [ ]:
import serial, time

bandPort = serial.Serial(port = "COM7", baudrate=9600, timeout=0.1, stopbits=serial.STOPBITS_ONE)

x_inp = []
FALL_THRES = 20

while(1):
        try:
            serialString = bandPort.readline().strip().decode("utf-8")
            inp = serialString.split(",")
            inp = list(map(float, inp))
            
            if(len(inp) == 6 and len(x_inp) > FALL_THRES):
                x_inp = x_inp[1:]
                y_pred = classifier.predict(sc.transform(x_inp))
                out = np.bincount(y_pred).argmax()
                print(np.bincount(y_pred))
                
                if (out == 0):
                    print("Its Not a Fall")
                elif(out == 1):
                    print("Its a Fall")

                bandPort.flush()
            elif(len(inp) == 6):
                x_inp.append(inp)
                
        except Exception:
            continue   